name: Cello
description: Cello is a Trello clone. A sort of kanban or task list app but on steroids. You can organise anything with it!
type: project
status:
  tag: on-hold
  description: "I was having some odd issues with `window.scrollTo` and `behaviour: smooth` which I need to work out."
keywords:
  ["cello", "trello", "task", "list", "kanban", "organise", "schedule", "plan"]
license: MIT
repository: https://github.com/sustained/cello
languages: [javascript]
technologies: [vue, vuex, vue-router, vue-draggable, axios, sass, json-server]
screenshots: []
