name: Voxels
description: Description
type: playground
status:
  tag: ongoing
  description: I'm struggling with how to implment multiple chunks basically, at this stage.
keywords:
  [
    "voxels",
    "minecraft",
    "terraria",
    "starbound",
    "clone",
    "3d",
    "rendering",
    "block",
    "game",
    "procedural",
    "generation",
    "mesh",
  ]
license: MIT
repository: https://github.com/sustained/sustained.name
languages: [javascript]
technologies: [three.js, three.js-orbitcontrols, simplex-noise]
screenshots: []
